// Auto-generated by scripts/generate-responsive-webp.py — do not edit by hand.
// Maps a source PNG path (as used in <img src>) to the WebP widths available
// alongside it (e.g. "/images/su-menh.png" -> "/images/su-menh-480w.webp").
export const imageManifest: Record<string, number[]> = {
  "/images/logo.jpg": [251],
  "/images/loi-ich-sbc.png": [480, 768, 1200],
  "/images/su-menh.png": [480, 768, 1200],
  "/images/tam-nhin.png": [480, 768, 1200],
  "/images/ocop/1. sp ocop.png": [480, 768, 1086],
  "/images/ocop/2. sp ocop.png": [480, 768, 1086],
  "/images/ocop/3. sp ocop.png": [480, 768, 1086],
  "/images/ocop/4. sp ocop.png": [480, 768, 1086],
  "/images/ocop/5. sp ocop.png": [480, 768, 1086],
  "/images/ocop/6. sp ocop.png": [480, 768, 1086],
  "/images/ocop/7. sp ocop.png": [480, 768, 1089],
  "/images/ocop/Giay ATVSTP.png": [480, 768, 995],
  "/images/ocop/sp tieu bieu.png": [480, 768, 1086],
  "/images/ocop/sp top 2.png": [480, 768, 1096],
  "/images/ocop/sp top.png": [480, 768, 1105],
  "/images/products/binh-ruou.png": [480, 768, 1086],
  "/images/products/cao-sam.png": [480, 768, 1060],
  "/images/products/ruou-dvt.png": [480, 768, 1024],
  "/images/products/ruou-tv.png": [480, 768, 988],
  "/images/products/sam-say.png": [480, 768, 1200],
  "/images/products/set-lau-2.png": [480, 768, 1200],
  "/images/products/set-lau.png": [480, 768, 1200],
  "/images/products/tra-hoa-sam.png": [480, 768, 1200],
};
