server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Hỗ trợ React Router (Client-side routing)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bỏ qua logs cho favicon và robots.txt
    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }
}
